import { TABLES } from '@/lib/api';

const activeField = { key: 'is_active', label: 'Active on site', type: 'checkbox' };
const featuredField = { key: 'is_featured', label: 'Featured', type: 'checkbox' };
const sortField = { key: 'sort_order', label: 'Sort Order', type: 'number', placeholder: '0' };

export const CONTENT_CONFIGS = {
  services: {
    table: TABLES.services,
    title: 'Services',
    addLabel: 'New Service',
    createTitle: 'New Service',
    editTitle: 'Edit Service',
    emptyText: 'No services yet',
    searchKeys: ['title', 'short_description', 'category'],
    searchPlaceholder: 'Search services...',
    orderBy: 'sort_order',
    titleKey: 'title',
    metaKey: 'category',
    descriptionKey: 'short_description',
    activeField: 'is_active',
    featuredField: 'is_featured',
    badges: [
      { key: 'category', label: 'Category' },
      { key: 'price_from', label: 'From', value: item => item.price_from ? `${item.price_from.toLocaleString()} ₸` : '' },
    ],
    fields: [
      { key: 'title', label: 'Title', placeholder: 'AI automation', wide: true },
      { key: 'slug', label: 'Slug', placeholder: 'ai-automation' },
      { key: 'category', label: 'Category', placeholder: 'AI / CRM / Web' },
      { key: 'short_description', label: 'Short Description', type: 'textarea', wide: true },
      { key: 'full_description', label: 'Full Description', type: 'textarea', rows: 5, wide: true },
      { key: 'price_from', label: 'Price From', type: 'number' },
      { key: 'price_to', label: 'Price To', type: 'number' },
      featuredField,
      activeField,
      sortField,
    ],
    empty: { title: '', slug: '', category: '', price_from: null, price_to: null, is_featured: false, is_active: true, sort_order: 0 },
  },
  products: {
    table: TABLES.products,
    title: 'Products / Ready Solutions',
    addLabel: 'New Product',
    createTitle: 'New Product',
    editTitle: 'Edit Product',
    emptyText: 'No ready solutions yet',
    searchKeys: ['title', 'short_description', 'category'],
    searchPlaceholder: 'Search products...',
    orderBy: 'sort_order',
    titleKey: 'title',
    metaKey: 'category',
    descriptionKey: 'short_description',
    activeField: 'is_active',
    featuredField: 'is_featured',
    badges: [
      { key: 'category', label: 'Category' },
      { key: 'implementation_price_from', label: 'Setup', value: item => item.implementation_price_from ? `${item.implementation_price_from.toLocaleString()} ₸` : '' },
      { key: 'subscription_price_from', label: 'Monthly', value: item => item.subscription_price_from ? `${item.subscription_price_from.toLocaleString()} ₸` : '' },
    ],
    fields: [
      { key: 'title', label: 'Title', placeholder: 'Oberon CRM', wide: true },
      { key: 'slug', label: 'Slug', placeholder: 'oberon-crm' },
      { key: 'category', label: 'Category', placeholder: 'CRM / AI / HoReCa' },
      { key: 'icon', label: 'Icon', placeholder: '📊' },
      { key: 'color', label: 'Accent Color', placeholder: '#4d7fff' },
      { key: 'short_description', label: 'Short Description', type: 'textarea', wide: true },
      { key: 'full_description', label: 'Full Description', type: 'textarea', rows: 5, wide: true },
      { key: 'implementation_price_from', label: 'Implementation From', type: 'number' },
      { key: 'implementation_price_to', label: 'Implementation To', type: 'number' },
      { key: 'subscription_price_from', label: 'Subscription From', type: 'number' },
      { key: 'subscription_price_to', label: 'Subscription To', type: 'number' },
      { key: 'features', label: 'Features', type: 'list', wide: true },
      { key: 'target_audience', label: 'Target Audience', type: 'list', wide: true },
      featuredField,
      activeField,
      sortField,
    ],
    empty: { title: '', slug: '', category: 'CRM', icon: '⚙️', color: '#4d7fff', features: [], target_audience: [], is_featured: false, is_active: true, sort_order: 0 },
  },
  cases: {
    table: TABLES.cases,
    title: 'Cases',
    addLabel: 'New Case',
    createTitle: 'New Case',
    editTitle: 'Edit Case',
    emptyText: 'No cases yet',
    searchKeys: ['title', 'client_name', 'industry', 'description'],
    searchPlaceholder: 'Search cases...',
    orderBy: 'sort_order',
    titleKey: 'title',
    metaKey: 'industry',
    descriptionKey: 'description',
    activeField: 'is_active',
    featuredField: 'is_featured',
    badges: [
      { key: 'client_name', label: 'Client' },
      { key: 'industry', label: 'Industry' },
    ],
    fields: [
      { key: 'title', label: 'Title', wide: true },
      { key: 'slug', label: 'Slug' },
      { key: 'client_name', label: 'Client Name' },
      { key: 'industry', label: 'Industry' },
      { key: 'image_url', label: 'Image URL' },
      { key: 'description', label: 'Description', type: 'textarea', rows: 4, wide: true },
      { key: 'result', label: 'Result', type: 'textarea', rows: 4, wide: true },
      { key: 'technologies', label: 'Technologies', type: 'list', wide: true },
      featuredField,
      activeField,
      sortField,
    ],
    empty: { title: '', slug: '', industry: '', technologies: [], is_featured: false, is_active: true, sort_order: 0 },
  },
  faq: {
    table: TABLES.faq,
    title: 'FAQ',
    addLabel: 'New Question',
    createTitle: 'New FAQ Item',
    editTitle: 'Edit FAQ Item',
    emptyText: 'No FAQ items yet',
    searchKeys: ['question', 'answer', 'category'],
    searchPlaceholder: 'Search FAQ...',
    orderBy: 'sort_order',
    titleKey: 'question',
    metaKey: 'category',
    descriptionKey: 'answer',
    activeField: 'is_active',
    badges: [
      { key: 'category', label: 'Category' },
      { key: 'sort_order', label: 'Order' },
    ],
    fields: [
      { key: 'question', label: 'Question', wide: true },
      { key: 'answer', label: 'Answer', type: 'textarea', rows: 5, wide: true },
      { key: 'category', label: 'Category' },
      sortField,
      activeField,
    ],
    empty: { question: '', answer: '', category: 'general', sort_order: 0, is_active: true },
  },
};
